import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "@/app/ui/root/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <Navbar />
          {children}</Providers>
      </body>
    </html>
  );
}
